# Generated by Django 4.1.1 on 2022-10-14 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('jdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.CharField(choices=[('new', 'NEW'), ('trending', 'TRENDING'), ('hot', 'HOT')], default='new', max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
